name: xlstm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda=12.1
  - cuda-nvcc=12.1
  - gxx_linux-64=11.2.0
  - python=3.11
  - pip
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - cmake #=3.28.2
  - pip:
      - pre-commit #==3.6.0
      - ipykernel #==6.29.0
      - dacite #==1.8.1
      - omegaconf #==2.3.0
      - torchmetrics #==1.3.0
      - tqdm #==4.66.1
      - pytest #==8.0.0
      - pytest-xdist #==3.5.0
      - numpy #==1.26.4
